include "/etc/bind/options.conf";

zone "au-team.irpo" {
    type master;
    file "/etc/bind/zone/au-team.irpo.db";
};

zone "10.10.in-addr.arpa" {
    type master;
    file "/etc/bind/zone/10.10.rev";
};
